import type { NextPage } from "next";
import Head from "next/head";

import React, { useEffect } from "react";
import Header from "../components/Header";
import { SidebarProvider } from "../context/SidebarContext";
import Faq from "../components/Faq";
import Footer from "../components/Footer";

import Hero from "../components/Hero";
import Newsletter from "../components/Newsletter";
import Pricing from "../components/Pricing";
import SocialProof from "../components/SocialProof";
import Testimonials from "../components/Testimonials";

import { useSession } from "next-auth/react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const { data: session, status } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (session && status === "authenticated") {
      router.push("/app");
    }
  }, [session, status, router]);

  return (
    <>
      <Head>
        <title>FIREway</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <SidebarProvider>
        <Header />
        <div className="flex dark:bg-gray-900 bg-white">
          <main className="order-2 mx-4 mt-4 flex-[1_0_16rem]">
            <Hero />
            <Newsletter />
            <SocialProof />
            <Testimonials />
            <Faq />
            <Pricing />
            <Footer />
          </main>
        </div>
      </SidebarProvider>
    </>
  );
};

export default Home;
